### PR TITLE
Adding package.json

### PR DESCRIPTION
**Pull request by zindel**
Hi Tommy,

I'd like to use your package with my Karma/Jasmine testing config. I've added very trivial and naive package.json. I'd appreciate if you could add it to the main branch, so that I can use your addition in my testing configuration with NPM.

Thanks,
    Oleksiy

### CODE REVIEW

**Comment by tommyh** [comment]
+1.

Rather than merge this as-is, I'd like to merge it in a way that I won't break it in the future.

What I'd like todo is switch the jasmine tests from a plain html page to the karma runner.  (This will also resolve an issue with the "documentation" tests and file:// issues, see readme.)

If you can do this I will merge very quickly.  If not, I will try to do it next but it might take a week or two for me to get to it.

Does that sound fair?

**Comment by zindel** [comment]
Hi Tommy,

Please review, what I've got here. I've changed the file structure some and removed all third-party libraries from the repository. package.json still needs a bit of help, (like adding repository, your email, probably some other meta information).

Let me know if it initially works for you and/or what would you add. I'm not very experienced in doing node packages, so likely missed something.

**Comment by zindel** [comment]
Couple bug fixes and making sure it works with require(). Also, it seems to me that we don't need to minify it. It will never work at runtime, but may be useful for developers to see the proper line/message if something breaks.

**Comment by tommyh** [comment]
Sorry for the lack of a response on this.  This is a great pull request and I'd love to merge it in.  This is next on my queue.  Thanks again for the hard work!

**Comment by tommyh** [comment]
Merged.  Thank you for the wonderful contribution!!

**Pull request closed without merging**
